### ISSUE TITLE
[Font-적용버그] Header, Signup 적용확인 / Footer Font적용불가

### ISSUE THREAD

**Issue by chochohee** [oreumi-dreamer/Dreamer#10]
globals.css에 전체선택자 되어있는데 footer부분만 기본글씨체 적용되는 문제있습니다.

**Comment by chochohee** [comment]
![image](https://github.com/user-attachments/assets/43014be4-14d6-40c8-be70-3ad19c5a5471)

**Comment by jihun-io** [comment]
`globals.css`에서 `html` 선택자에 `font-family: var(--font-family)`를 지정하고, `body` 선택자에 `font-family: inherit` 속성을 지정하여 문제를 해결했습니다.
