### ISSUE TITLE
[Main page] more-btn 모달 위치 bug

### ISSUE THREAD

**Issue by jini0012** [oreumi-dreamer/Dreamer#101]
### 🚨12.17 [Main page] more-btn 모달 위치 bug
![image](https://github.com/user-attachments/assets/deda2817-74ed-440c-b00a-d52b3951208f)

**Comment by chochohee** [comment]
![image](https://github.com/user-attachments/assets/51c1c41b-a3fb-42b1-b394-fc78b31c07a4)
해결완료
