### ISSUE TITLE
[tomong] 해몽된 꿈목록 레이아웃 어긋나는문제

### ISSUE THREAD

**Issue by chochohee** [oreumi-dreamer/Dreamer#113]
![image](https://github.com/user-attachments/assets/2cf6f13d-7008-4558-a35c-10860bbab5fc)

**Comment by jini0012** [comment]
### 12.18 🐛 해몽 꿈 선택 및 해몽된 꿈목록 레이아웃 어긋나는 문제 수정
> 글 3개 이상 있는 계정

![image](https://github.com/user-attachments/assets/8169eb31-f519-4f24-b4ab-e0a5a774af83)

> 글 1개 있는 계정

![image](https://github.com/user-attachments/assets/59efcdee-122f-4bd0-8761-d9ef292dc8a4)
