### ISSUE TITLE
[API] .png 파일 배경 색이 black이 되는 이슈

### ISSUE THREAD

**Issue by chochohee** [oreumi-dreamer/Dreamer#130]
![image](https://github.com/user-attachments/assets/bf27b510-15d2-4496-a58c-5a6a8b22ed32)

**Comment by jihun-io** [comment]
<img width="952" alt="image" src="https://github.com/user-attachments/assets/bd293ccb-1073-467e-8cdb-c93e0bd1e339" />
API를 수정하여 문제를 해결했습니다.
