### ISSUE TITLE
[Profile Edit] 프로필 사진 수정 완료 후 헤더, 글쓰기 모달 에 사진 바뀌지 않는 bug

### ISSUE THREAD

**Issue by jini0012** [oreumi-dreamer/Dreamer#136]
### 🚨12.18 [Profile Edit] 프로필 사진 수정 완료 후 헤더에 사진 바뀌지 않는 bug
> 사진이 변경된 사진이 아닌 기본 rabbit.svg 파일로 적용되는 bug가 있습니다.

![image](https://github.com/user-attachments/assets/8cdad9ea-46e6-41e0-9e48-1a436108c10e)

**Comment by jini0012** [comment]
> 바로 글쓰기 모달 open 시 위와 같은 bug 가 추가로 확인되었습니다

![image](https://github.com/user-attachments/assets/ad284216-c0a0-4d7d-85ea-08ada59e22ff)

**Comment by jihun-io** [comment]
수정 완료 시 실행되는 ```router.push(`/users/[userId]`)``` 코드를 ```location.href = `/users/[userId]```로 수정하여 문제를 해결했습니다.
