### ISSUE TITLE
[Post] 서버와 통신중 댓글작성 다회클릭시 여러번남겨짐이슈

### ISSUE THREAD

**Issue by chochohee** [oreumi-dreamer/Dreamer#137]
![image](https://github.com/user-attachments/assets/587b9562-8595-4c39-acec-bd90c9dcd3f1)

**Comment by jini0012** [comment]
### 12.18 🐛 댓글 작성 여러번 클릭 시 모두 댓글 등록되는 부분 수정 완료
- 댓글 submit 될 경우 버튼 disable 적용 및 UI가 버튼이 아닌 Loading (mini-circle) 로 구현
