### ISSUE TITLE
[Main page] 메인 포스트 하단 더보기 버튼 클릭 후 뜨는 포스트들 클릭 시 모달 안뜨는 bug

### ISSUE THREAD

**Issue by jini0012** [oreumi-dreamer/Dreamer#147]
### 🚨 12.18  [Main page] 메인 포스트 하단 더보기 버튼 클릭 후 뜨는 포스트들 클릭 시 모달 안뜨는 bug

**Comment by jihun-io** [comment]
https://github.com/oreumi-dreamer/Dreamer/pull/156
