### ISSUE TITLE
[PostModal] 댓글작성 서버통신시 로딩아이콘 위치조정

### ISSUE THREAD

**Issue by chochohee** [oreumi-dreamer/Dreamer#152]
기존 레이아웃보다 살짝 하단에 위치하고있어서 조금 위로 위치 옮겨주세용

**Comment by jini0012** [comment]
### 💄 12.18 [PostModal] 댓글작성 서버통신시 로딩아이콘 위치조정
![image](https://github.com/user-attachments/assets/fb93a9dd-7e0e-419b-bcda-7ce28387172e)
