### ISSUE TITLE
[PostModal] max-width 720px기점부터 기본스크롤바적용됨

### ISSUE THREAD

**Issue by chochohee** [oreumi-dreamer/Dreamer#167]
![image](https://github.com/user-attachments/assets/745a2c49-d63f-435f-83b1-5d01a6dbf99c)

**Comment by jihun-io** [comment]
<img width="705" alt="image" src="https://github.com/user-attachments/assets/fe66caf6-8bca-439f-8a47-66fae0eb9a1a" />

기본 스크롤 바의 스타일을 720px 미만 모달에도 적용하여 문제를 해결했습니다.
