### ISSUE TITLE
[HeaderModal] 헤더의 계정 설정 버튼을 Link로 변경했을 시 스타일이 깨지는 문제

### ISSUE THREAD

**Issue by jihun-io** [oreumi-dreamer/Dreamer#18]
<img width="394" alt="image" src="https://github.com/user-attachments/assets/21e05b3b-5aef-4c4a-b892-68d2394d0825">

계정 설정 버튼을 Link로 전환 시 스타일링이 깨지는 문제가 발생했습니다.

**Comment by chochohee** [comment]
![image](https://github.com/user-attachments/assets/ecb3d9c6-6f03-49ff-8cb4-4430250fb019)
button 태그에 LINK태그 씌운 후 href 연결
