### ISSUE TITLE
[팔로우/팔로워] 아이디/닉네임 최대글자 레이아웃깨짐

### ISSUE THREAD

**Issue by chochohee** [oreumi-dreamer/Dreamer#186]

**Comment by jihun-io** [comment]
<img width="548" alt="image" src="https://github.com/user-attachments/assets/22fa454d-b37a-426f-b234-948d945dbbf4" />
`.profile-form-info`에 `word-break: break-all;` 속성을 부여하여 문제를 해결했습니다.
