### ISSUE TITLE
[Write] 해시태그모달 라벨 동작안됨

### ISSUE THREAD

**Issue by chochohee** [oreumi-dreamer/Dreamer#187]
![image](https://github.com/user-attachments/assets/f802ed11-12b2-4f0b-91ed-40618133ecce)

**Comment by hanj33** [comment]
[오류 확인]

프로필에 작성한 게시글이 없을 때 "글 쓰러 가기" 버튼을 누르면 발생하는 문제. 헤더의 "글쓰기" 버튼을 눌렀을 땐 라벨을 눌렀을 때 체크박스가 제대로 동작함.
그런데 "글 쓰러 가기" 버튼을 눌러 글작성 모달을 열었을 때, 해시태그/기분 모달의 라벨을 누를 경우 체크박스 아이콘은 동작하지 않으나 체크했다는 정보는 인식함... → 작성되지 않는 오류로 인해 모달을 닫고 헤더 버튼을 눌러 새로운 모달을 열면 저장된 데이터가 뜨는 걸 볼 수 있음

+ 비공개 라벨 제대로 동작 안 함. 함께 확인할 것.

**Comment by chochohee** [comment]
![image](https://github.com/user-attachments/assets/13746c5a-b65b-4c2d-8cb0-83d764da372c)
헤더에서 모달오픈에대한 예외처리가 Narrow에만 되어있어서, Wide헤더인 상태에서 계속 Write Dialog가 Dom에 road되어있는 상태라 지속 오류 발생 예외처리 및 해결 완료
