### ISSUE TITLE
[PostModal] HTML/CSS

### ISSUE THREAD

**Issue by chochohee** [oreumi-dreamer/Dreamer#2]
글쓰기 Modal

**Comment by jini0012** [comment]
### ✨ 12.03 PostModal JS 기능 추가
1. 모달 닫기 기능 구현 (dimmed, close button)
- 댓글 입력 중 close 되는 부분 개선 > 댓글 입력 중에 모달 밖으로 벗어나려는 경우, confirm 으로 종료 여부 재 확인
2. 좋아요, 스크랩 button click event 구현 및 상태 관리
3. 댓글 입력 시 값 상태 관리
4. 댓글 입력 article 내 꿈해몽, 비공개 checkbox 상태 관리
---
### 🎨 기능 구현 예정
1. 댓글 확인 article : 댓글 길이가 길 때 클릭 시 전체 댓글 open 기능 구현중

**Comment by jini0012** [comment]
### ✨12.04 PostModal
1. 댓글 창 css 디자인 변경으로 HTML/CSS 수정 완료

**Comment by jini0012** [comment]
### 💄 12.05 PostModal
1. 댓글 창 css 디자인 변경으로 css 수정 완료
2. 커스텀 체크박스 구현 완료
3. 반응형 css 일부 구현
