### ISSUE TITLE
[tomong] 토몽이 인삿말 / 댓글 잘림

### ISSUE THREAD

**Issue by chochohee** [oreumi-dreamer/Dreamer#201]
![image](https://github.com/user-attachments/assets/2464f3cf-e1a0-451d-a639-e96f2e368f2e)

**Comment by jihun-io** [comment]
<img width="559" alt="image" src="https://github.com/user-attachments/assets/0d374cc1-8f85-4d3a-a4b5-ad5beb534717" />

인사하는 토몽 이미지를 높이에 따라 반응하도록 수정했고, 그럼에도 공간이 부족할 시에는 버튼과 토몽 이미지를 겹치도록 하여 문제를 수정했습니다.
