### ISSUE TITLE
[Join] 이메일 입력 필드의 인증 코드 발송 버튼이 input을 가리는 현상

### ISSUE THREAD

**Issue by jihun-io** [oreumi-dreamer/Dreamer#214]
<img width="568" alt="image" src="https://github.com/user-attachments/assets/9892ad3c-126e-4886-95e3-8d4c0eb03631" />

**Comment by jini0012** [comment]
### 🐛 12.20 [Join] 이메일 입력 필드의 인증 코드 발송 버튼이 input을 가리는 현상 수정 완료
#223 merge 내  input 내부 padding 적용하여 수정 완료되었습니다
