### ISSUE TITLE
[ProfileEdit] ProfileEdit / Footer 겹침현상발생

### ISSUE THREAD

**Issue by chochohee** [oreumi-dreamer/Dreamer#237]
![image](https://github.com/user-attachments/assets/827c2894-19b0-4595-b48d-74122e39a29e)
width 1170px지점쯤, ProfileEdit / Footer 겹침현상발생

**Comment by jini0012** [comment]
### 🐛 [ProfileEdit] ProfileEdit / Footer 겹침현상발생 수정 완료
![image](https://github.com/user-attachments/assets/4a0c2746-8672-4483-b812-c10c1f90cd3f)
