### ISSUE TITLE
[Profile/Footer] 추천Dreamer 팔로우시 프로필상 즉각반영 안됨

### ISSUE THREAD

**Issue by chochohee** [oreumi-dreamer/Dreamer#238]
![image](https://github.com/user-attachments/assets/37a5935d-c09f-4930-8b8e-e79759902a11)

**Comment by jihun-io** [comment]
https://github.com/user-attachments/assets/0c85303d-b5af-4e63-9111-c614f089b741

Redux로 팔로잉 및 팔로워 수 상태를 관리하여 문제를 해결했습니다.
