### ISSUE TITLE
[UI] 메인 스크롤바 UI 버그

### ISSUE THREAD

**Issue by chochohee** [oreumi-dreamer/Dreamer#38]
![image](https://github.com/user-attachments/assets/d2309c73-6c82-48c5-9900-2f443be70b95)

보여선 안되는 UI가 보이는 버그가있습니다.

**Comment by jihun-io** [comment]
.main-container의 `overflow: scroll` 속성을 제거하여 문제를 해결했습니다.

```
.main-container {
  padding: 16.6rem 0 0 0;
  background-color: var(--background-color);
}
```
