### ISSUE TITLE
[PostModal] 메인페이지/프로필페이지에서 모달활성화시 딤드에서 스크롤되는문제 발생

### ISSUE THREAD

**Issue by chochohee** [oreumi-dreamer/Dreamer#50]

**Comment by jini0012** [comment]
### 🐛 12.12 [PostModal] 메인페이지/프로필페이지에서 모달활성화시 딤드에서 스크롤되는 bug 수정

PostModal css 내 `html:has(.post-modal) { overflow: hidden; }` 추가하여 오류 수정되었습니다.
