### ISSUE TITLE
[PostModal] 장르태그 모드에따른 컬러변경

### ISSUE THREAD

**Issue by chochohee** [oreumi-dreamer/Dreamer#54]

**Comment by jini0012** [comment]
### 🎨 12.12 [PostModal] 장르 태그 모드에 따른 컬러 변경
1. constants.js 내 darkMode 색상 값 적용
2. PostModal 내 Redux 상태 값 `light` 일경우 lightColor 적용 / `dark` 인경우 darkColor 적용 / `deviceMode` 인경우 `window.matchMedia("(prefers-color-scheme: light)").matches)` 값으로 기기가 `light` 인지 확인 후 `true` 이면 lightColor 적용
