### ISSUE TITLE
[MainPage] 재로그인 시 더보기 모달이 없어지지 않는 문제

### ISSUE THREAD

**Issue by hanj33** [oreumi-dreamer/Dreamer#55]
더보기 모달을 통해 로그아웃 후, 다시 로그인할 경우 더보기 모달이 떠있음(로그아웃 이전, 더보기 모달을 띄운 것과 동일한 상태)

**Comment by chochohee** [comment]
Header 컴포넌트에 useEffect를 통해 컴포넌트가 처음 마운트 될때 Redux의 closeModal을 실행하도록 수정함
