### ISSUE TITLE
[Main Page] 메인 페이지 전체 화면으로 볼 때 아티클 늘어나는오류

### ISSUE THREAD

**Issue by jini0012** [oreumi-dreamer/Dreamer#67]
### 🚨12.13 [Main Page] 메인 페이지 전체 화면으로 볼 때 아티클 늘어나는오류
![image](https://github.com/user-attachments/assets/7c03ff54-37b7-49cd-96bd-d353eb7b9719)

**Comment by jihun-io** [comment]
<img width="895" alt="image" src="https://github.com/user-attachments/assets/f5af93f2-146d-4671-98cf-c63a59453445" />
article의 너비를 조정하여 문제를 해결했습니다.
