### ISSUE TITLE
[SignupPage] 2차 HTML/CSS

### ISSUE THREAD

**Issue by chochohee** [oreumi-dreamer/Dreamer#7]
CSS 스타일링

**Comment by jini0012** [comment]
12.03 HTML/CSS 진행 예정이었으나, Figma 디자인 변경 중으로, 변경 후 구현 예정

**Comment by jini0012** [comment]
📝💄  12.05 PostModal 마크업 및 스타일 수정
1. Header 분리하여 마크업 적용
2. main 첫페이지 (BasicinfoForm) 마크업 및 css 수정 중
---
📝💄 구현 예정
1. BasicinfoForm 마무리 및 ProfileForm 진행 예정
2. 디자인 변경으로 BasicinfoForm 내 생일 (일) input 태그 -> select 태그로 변경 예정

**Comment by jini0012** [comment]
### 📝💄 12.06 PostModal 마크업 및 스타일 수정
1. signup 첫페이지 (BasicinfoForm) 마크업 및 css 구현 중
