### ISSUE TITLE
[DropDown] Profile, PostModal에 더보기 버튼 모달 붙이기

### ISSUE THREAD

**Issue by chochohee** [oreumi-dreamer/Dreamer#74]

**Comment by jini0012** [comment]
### ✨ 12.14 [DropDown] PosrModal 내 더보기 버튼 모달 붙이기 완료 

> isMyPost

![image](https://github.com/user-attachments/assets/a4234b37-2831-4fe4-a1c1-4e9f15639f17)

> isNotMyPost

![image](https://github.com/user-attachments/assets/5b048131-e619-42df-99e6-e3c44a6b8548)


💄  더보기 버튼 모달 내 text 위치 왼쪽으로 붙임 현상 발생하여  css 수정되었습니다.
`.drop-down-items .drop-down-item` 선택자 `display: flex;,  align-items: center;, justify-content: center;` 적용으로 수정

**Comment by jini0012** [comment]
✨ 12.14 [DropDown] Profile 내 더보기 버튼 모달 붙이기 완료
| isMyPost

![image](https://github.com/user-attachments/assets/c445dbea-5b48-414a-aa25-bc661751abb1)

> isNotMyPost

![image](https://github.com/user-attachments/assets/ae3d5886-8bfe-41d5-afe7-855454adcc62)


> 추가 확인 필요 사항

위치 위와 같이 적용할지 아래 사진과 같이 post 내로 보이게 적용할지 팀원 확인 필요
![image](https://github.com/user-attachments/assets/3d11a022-c7a8-4874-bb90-fe3b126514d5)
